# Generated by Django 6.0.6 on 2026-06-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderRequest',
        ),
    ]
